### ISSUE TITLE
I built this using ubuntu, but I want to use the tools on windows, what do I do with this files? 

### ISSUE THREAD

**Issue by Arthurfogo7** [rschlaikjer/mangetsu#1]
![image](https://user-images.githubusercontent.com/85951083/197586433-02359ff0-1539-4857-b351-1752731d928e.png)

![image](https://user-images.githubusercontent.com/85951083/197639395-205a0ffe-e655-4572-8c54-31abab412c95.png)

(I tried to run on the terminal, but nothing happens)

**Comment by dtlnor** [comment]
you should input its folder/file. as the prompt shows
