### ISSUE TITLE
NXCXA decompress

### ISSUE THREAD

**Issue by Dimoks** [rschlaikjer/mangetsu#3]
Cannot decompress NXCXA file. Here's an example.
[allui.00000011.MENU_PARTS_EN.NXZ.zip](https://github.com/rschlaikjer/mangetsu/files/13968078/allui.00000011.MENU_PARTS_EN.NXZ.zip)

**Comment by rschlaikjer** [comment]
Fixed, wrong return code check from inflate.

**Comment by Dimoks** [comment]
Another file
[allpachdml.00000004.IMG0000.NXZ.zip](https://github.com/rschlaikjer/mangetsu/files/14076098/allpachdml.00000004.IMG0000.NXZ.zip)
